modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
	modId="pickpick" #mandatory
	version="${file.jarVersion}"
	displayName="Pick Pick"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/pick-pick"
	issueTrackerUrl="https://github.com/kregerl/PickPick/issues"
	logoFile="PickPickLogo.png" 
	credits=""
	authors="AreUThreateningMe"
	description='''
	Adds a pick tool feature that is similar to vanilla pick block, but instead of swapping items it places the correct tool in your hotbar.
	'''
[[dependencies.pickpick]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.pickpick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="AFTER"
    side="BOTH"
